# Generated by Django 6.0.4 on 2026-04-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
