# Generated by Django 6.0.4 on 2026-04-14 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('single_elimination', 'Single Elimination')], max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_round', models.IntegerField(default=1)),
                ('auto_generate_matches', models.BooleanField(default=True)),
                ('allow_draws', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teams', models.ManyToManyField(related_name='tournaments', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundRobinGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teams', models.ManyToManyField(related_name='round_robin_groups', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('stage', models.CharField(choices=[('play_in', 'Play-in Round'), ('round_of_16', 'Round of 16'), ('quarter_finals', 'Quarter Finals'), ('semi_finals', 'Semi Finals'), ('finals', 'Finals'), ('third_place', 'Third Place Match')], max_length=50)),
                ('match_format', models.CharField(choices=[('bo1', 'Best of 1'), ('bo3', 'Best of 3'), ('bo5', 'Best of 5')], default='bo1', max_length=10)),
                ('team_a_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('team_b_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournament.match')),
                ('parent_match_a', models.ForeignKey(blank=True, help_text='Match that feeds into team_a position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_match_a', to='tournament.match')),
                ('parent_match_b', models.ForeignKey(blank=True, help_text='Match that feeds into team_b position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_match_b', to='tournament.match')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='teams.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament')),
            ],
            options={
                'ordering': ['tournament', 'round_number', 'stage'],
                'unique_together': {('tournament', 'round_number', 'team_a', 'team_b')},
            },
        ),
    ]
