# Generated by Django 6.0.4 on 2026-04-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['tournament', 'round_number', 'game_number']},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='game_number',
            field=models.IntegerField(blank=True, help_text='Game number within the round', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'round_number', 'game_number')},
        ),
    ]
