# Generated by Django 6.0.4 on 2026-04-15 08:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_waitinglist_player'),
        ('tournament', '0002_alter_match_options_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'game_number']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='allow_draws',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='auto_generate_matches',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='match',
            name='game_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('bo1', 'Best of 1'), ('bo3', 'Best of 3'), ('bo5', 'Best of 5')], default='bo3', max_length=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='parent_match_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_match_a', to='tournament.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='parent_match_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_match_b', to='tournament.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('qualifier', 'Qualifier'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('third_place', 'Third Place Playoff'), ('group_stage', 'Group Stage')], default='qualifier', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team_a', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team_b', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('round_robin', 'Round Robin')], default='single_elimination', max_length=20),
        ),
        migrations.DeleteModel(
            name='RoundRobinGroup',
        ),
    ]
