# Generated by Django 6.0.4 on 2026-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_match_options_remove_match_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('play_in', 'Play-In Round'), ('qualifier', 'Qualifier'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('third_place', 'Third Place Playoff'), ('group_stage', 'Group Stage')], default='qualifier', max_length=20),
        ),
    ]
