# Generated by Django 6.0.4 on 2026-04-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_match_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'game_number', 'bracket_type']},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_type',
            field=models.CharField(blank=True, choices=[('winners', 'Winners Bracket'), ('losers', 'Losers Bracket'), ('grand', 'Grand Finals')], default='winners', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_feeds_into', to='tournament.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round_lb',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round_wb',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('play_in', 'Play-In Round'), ('qualifier', 'Qualifier'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('third_place', 'Third Place Playoff'), ('group_stage', 'Group Stage'), ('winners_final', 'Winners Final'), ('losers_final', 'Losers Final'), ('grand_final', 'Grand Final')], default='qualifier', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'round_number', 'game_number', 'bracket_type')},
        ),
    ]
