# Generated by Django 6.0.4 on 2026-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_waitinglist_player'),
        ('tournament', '0005_alter_match_options_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_number', 'bracket_type'], name='tournament__tournam_2e53a2_idx'),
        ),
    ]
