# Generated by Django 5.0.2 on 2026-04-20 16:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_waitinglist_player'),
        ('tournament', '0006_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bye_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bye_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_source_type',
            field=models.CharField(blank=True, choices=[('winner', 'Winner'), ('loser', 'Loser')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_source_type',
            field=models.CharField(blank=True, choices=[('winner', 'Winner'), ('loser', 'Loser')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='bracket_type',
            field=models.CharField(blank=True, choices=[('winners', 'Winners Bracket'), ('losers', 'Losers Bracket'), ('grand', 'Grand Finals'), ('grand_reset', 'Grand Finals Reset')], default='winners', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('play_in', 'Play-In Round'), ('qualifier', 'Qualifier'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('third_place', 'Third Place Playoff'), ('group_stage', 'Group Stage'), ('winners_final', 'Winners Final'), ('losers_final', 'Losers Final'), ('grand_final', 'Grand Final'), ('grand_final_reset', 'Grand Final Reset')], default='qualifier', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('bye', 'Bye')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
