# Generated by Django 6.0.4 on 2026-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('primary_role', models.CharField(choices=[('gold_lane', 'Gold Lane'), ('exp_lane', 'Exp Lane'), ('mage', 'Mage'), ('tank_support', 'Tank/Support'), ('jungler', 'Jungler')], max_length=50, verbose_name='Primary Role')),
                ('secondary_roles', models.CharField(blank=True, default='', help_text='Select multiple secondary roles separated by commas', max_length=500, verbose_name='Secondary Roles')),
                ('current_rank', models.CharField(choices=[('warrior', 'Warrior'), ('elite', 'Elite'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('epic', 'Epic'), ('legend', 'Legend'), ('mythic', 'Mythic'), ('mythical_honor', 'Mythical Honor'), ('mythical_glory', 'Mythical Glory')], max_length=50, verbose_name='Current Rank')),
                ('highest_rank', models.CharField(choices=[('warrior', 'Warrior'), ('elite', 'Elite'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('epic', 'Epic'), ('legend', 'Legend'), ('mythic', 'Mythic'), ('mythical_honor', 'Mythical Honor'), ('mythical_glory', 'Mythical Glory')], max_length=50, verbose_name='Highest Rank Reached')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-current_rank', 'name'],
            },
        ),
    ]
